### ISSUE TITLE
Support for Multiple Inboxes with Separate Credentials in MailPit

### ISSUE THREAD

**Issue by deepakplay** [axllent/mailpit#115]
I'm regularly encountering issues with managing multiple email accounts in different contexts, different projects. Currently, MailPit only supports a single inbox, which makes it difficult to separate and manage multiple project and work as a team.

I would love to see a feature in MailPit that supports multiple inboxes with separate smtp credentials. This would allow users to add, manage, and switch between different email accounts seamlessly.

### Proposed feature details:

**Add new account:** Allow users to add new email accounts to MailPit by providing the necessary credentials. These credentials should be stored and associated with the corresponding inbox.

**Switch between inboxes:** A simple and  UI element (such as a dropdown or side menu) should be present to allow users to switch between their various inboxes with a single click.

**Separate settings for each inbox:** Each inbox should have its own settings/preferences. This allows each account to be customized according to its purpose and usage.

Refer: Mailtrap email testing feature

Please let me know if there are any plans to implement such a feature. Thank you for your consideration.

**Comment by axllent** [comment]
Hi @deepakplay. Simply put, no, this is not planning (please see #86). Whilst such a feature would be awesome, it would require a complete rewrite of most of the logic in Mailpit in order to handle multiple accounts, each with their own mailbox, routing, and permissions, not to mention administration, password resets etc.

It sounds to me like you should just be using something like [Mailtrap](https://mailtrap.io/) which already exists (it's just not locally hosted and costs money).
