### ISSUE TITLE
Feature Request: Set HELO

### ISSUE THREAD

**Issue by kjake** [axllent/mailpit#146]
Within Docker, the HELO response seems locked into localhost, even thought I've set a hostname when launching the container.  Could you add an option for us to configure the HELO at runtime, or use the hostname automatically?

thanks!

**Comment by axllent** [comment]
Hi there. I'm confused because the `HELO` response isn't locked to "localhost", and it already uses the current hostname in the response, not that the response (beyond the `250`) is mandatory.
```
telnet 192.168.7.2 1025
Trying 192.168.7.2...
Connected to 192.168.7.2.
Escape character is '^]'.
220 abf5fb0499d6 Mailpit ESMTP Service ready
HELO 192.168.7.2
250 abf5fb0499d6 greets 192.168.7.2
```

... where `abf5fb0499d6` is the hostname of my docker container running Mailpit, and `192.168.7.2` is the IP of my docker server. It sounds to me that you are connecting to `localhost` so your client is sending a `HELO localhost`, and is thus receiving a `...greets localhost` in the response.

What is it that you are trying to achieve exactly?

**Comment by daqqad** [comment]
It would actually be useful to be able to override HELO string @axllent 

My specific use case is GMail's relay service which rejects any HELO string that isn't configured as one of the domains on the account.

I made a few simple changes to implement this via an extra variable in config file for relay and it is working in my environment.

Can I push a branch for you to check out the changes and hopefully approve?

**Comment by axllent** [comment]
@daqqad I'm not sure what impact your approach would have, so maybe best you sent a PR so I can see. Can't promise anything, but we can continue the discussion there. Please note that I'm currently very busy, so it may take a couple of days to review and get back to you, thanks.

**Comment by petek** [comment]
@daqqad Don't know if you still have this issue, and the fix has been committed to the project for the next release.

**Comment by daqqad** [comment]
> [@daqqad](https://github.com/daqqad) [@kjake](https://github.com/kjake) Don't know if you still have this issue, and the fix has been committed to the project for the next release.

I totally missed this reply, but thank you.
