### ISSUE TITLE
Feature Request: Pass search query parameters from the main URL

### ISSUE THREAD

**Issue by bcremer** [axllent/mailpit#156]
# Feature Request

Allow query parameters from the `api/v1/search` to be passed via the main Browser URL like so:
https://mailpit.local/?query=from:ticket-34745@project.local&limit=5

## Use case
We running a shared mailpit instance for a large number of testsystems that all create mails in the mailpit instance using different `from` addresses.

We want to add a direct link in the ticket system to the mailpit instance filtered to a from address that matches the ticket.

**Comment by axllent** [comment]
Hi @bcremer, thanks for the feedback. Currently this is not possible as it would require the ability to parse URL parameters on the frontend which Mailpit does not have. In order to achieve this, the Vue frontend would need to to use URL routing which would mean a rather large rewrite of several core UI components as it would also impact every other aspect of the UI too (filtering , pagination, messages, etc).

This feature is however already "planned", or rather I have been strongly considering this for future changes. I just don't know when that will happen as it requires a fair amount of time to write / adapt. I will leave this open as a reminder :)

**Comment by axllent** [comment]
I have just released [v1.9.0](https://github.com/axllent/mailpit/releases/tag/v1.9.0) which includes virtual routing. You cannot however set the pagination limit, but you can link directly to searches, eg: `https://mailpit.local/search?q=from:ticket-34745@project.local`

**Comment by axllent** [comment]
I'm closing this as complete, but feel free to reopen if you have issues.

**Comment by bcremer** [comment]
Works like a charm. Thank you.
