### ISSUE TITLE
Feature Request: Print email content only

### ISSUE THREAD

**Issue by mfrieling** [axllent/mailpit#157]
Currently the browser print function prints the whole Mailpit window but doesn't scroll the mail content iframe. Thus the email itself is cut off and only partially printed. It would be helpful to have a print function (mainly or HTML but possibly for Text as well) which only prints the iframe content. This way the email content could be saved as PDF for further discussion with customers. This is especially important when the email under development doesn't yet look as expected in certain clients and therefore releasing and sending it to the customer makes no sense as his client would display it wrong.

**Comment by axllent** [comment]
@mfrieling I do not think that having the ability to print either to paper or PDF will do what you are wanting for the following reasons:
1. The browser's support for printing is very limited as it automatically tries to generate a printer-friendly version of whatever you are trying to print. This often includes skipping things like background images, modified widths, font-resizing, re-aligned images etc, and won't accurately reflect the message you are trying to print.
2. Printed widths are very unpredictable and definitely not what you see on screen.

If anything, what you actually need is probably a screenshot of the email rather than a "printed" version. The issue here is that tools like [html2canvas](https://github.com/niklasvh/html2canvas) or [modern-screenshot](https://github.com/qq15725/modern-screenshot), which use JavaScript to render a screenshot image of a page (or the HTML message in this case), do not simply allow all remote images/files (a standard browser security feature). This security policy complicates matters as all remote assets then need to be proxied via Mailpit so the browser "sees" them as all coming from the same host as Mailpit. Technically this would work (I think, with enough work), however if Mailpit is running for instance in a docker environment, then there is a chance it doesn't have direct access to the assets (eg: local DNS) like your browser does, and this would result in missing images in the screenshot.

I will keep experimenting with a few potential screenshot solutions, but I can't promise anything at this stage.

**Comment by axllent** [comment]
The ability to take screenshots has been released with v1.8.3
