### ISSUE TITLE
Feature request: delete multiple emails at once

### ISSUE THREAD

**Issue by asaah18** [axllent/mailpit#164]
I think it would be great to be able to select and delete multiple emails at once. Or delete all emails except the one that has a tag

**Comment by axllent** [comment]
You can already select multiple messages at a time using Ctrl-click, or Shift-click - and then delete :)

**Comment by asaah18** [comment]
I didn't notice that I can do that, thank you. 
But what about deleting all messages except the ones with tags?

**Comment by axllent** [comment]
I will look into a `is:untagged` search option at some point, but this is currently not possible. You can definitely exclude messages containing tags in a search (eg `!tag:mytag`), but there is currently no option to filter by messages containing no tag.

**Comment by asaah18** [comment]
> don't know of any email clients that have such functionality. Why is something like this so desirable, when this is a tool mostly for development purposes? The closest functionality that could be justified would be a filter or search for untagged emails. Then you could manually select and delete them all.

In my case, testing emails start to clutter and want delete all of the cluttered emails but keep an email or two that are used as a reference -as I am trying to recreate the email html that have multiple cases- .

**Comment by axllent** [comment]
I don't think (at this stage) locking messages is a good move, as this will potentially all sorts of confusion and complications, and I believe that such functionality is becoming far too personal / specific-user-focused. There are potentially already existing ways to handle this, such as to add a tag (eg: `keep`) to the messages you want to keep. If you do decide to manually prune, search to `!tag:keep` which will find all messages that do not have the "keep" tag, and delete from there.

I have already (in my local development branch, not yet in github) added the `is:tagged` search option (or `!is:tagged` if you wanted those without any tags) which is the original request here. I believe that this, as well as the proposed "`keep` solution" will achieve both requests here?

Mailpit does not yet have a "delete all" for a filtered view, only "delete 50" (ie: those displayed on-screen). I am in the middle of a complete frontend rewrite (relating to #156) which is actually taking far longer than I had initially though, mainly because I'm breaking up all the frontend components into logical and manageable parts. The API is currently the same as before (with the addition of the `is:tagged` search), so I'm going to have to consider how I could handle the "delete all" for a filtered view (including those not displayed on the current page).

**Comment by asaah18** [comment]
It's all good as long as there's a way to delete all emails except certain ones somehow

**Comment by axllent** [comment]
I have just released [v1.9.0](https://github.com/axllent/mailpit/releases/tag/v1.9.0) which has changes relating to this issue. The web UI now provides the ability to delete all messages matching a search, so you could for instance search for all messages not tagged (`!is:tagged`) or for all messages not tagged with your "to keep" tag (whatever that may be) and delete.

**Comment by axllent** [comment]
I'm closing this as complete, but feel free to reopen if you have issues.
