### ISSUE TITLE
Japanese, Chinese, or Korean text not showing up properly

### ISSUE THREAD

**Issue by rogerdz** [axllent/mailpit#18]
I have Maipit running on a Docker container, with the following command:
`docker run -d \
--restart unless-stopped \
--name=mailpit \
-p 8025:8025 \
-p 1025:1025 \
axllent/mailpit`

![2022-10-18_01-09](https://user-images.githubusercontent.com/78783748/196251144-5b94d70e-ce35-4029-86d8-a3c3f5485f08.png)
![2022-10-18_01-10](https://user-images.githubusercontent.com/78783748/196251190-8c33fb68-039c-4849-8345-b529b258216d.png)

**Comment by axllent** [comment]
Thank you. Are you able to attach an example email to this issue so I can do further testing please?

**Comment by rogerdz** [comment]
I attach example mail:
[57646be0-8dbe-4ebf-89b4-fd5c32fda3d8.zip](https://github.com/axllent/mailpit/files/9805860/57646be0-8dbe-4ebf-89b4-fd5c32fda3d8.zip)

I use command line for test send mail: 
`echo -e "To:receiver1@domain1, receiver2@domain2 \nSubject:Subject of email 熟語ルビの例 일욜에 만나~ 读写汉字 اثنا عشر شهرا في كتاب Tiếng việt \n\nBody of email. 熟語ルビの例 일욜에 만나~ 读写汉字 اثنا عشر شهرا في كتاب Tiếng việt\n" | /usr/sbin/sendmail -f sender@domain -F sendername -it`

**Comment by axllent** [comment]
Thank you. I can confirm the issue, I'm just not sure what to do about it. I'll do a bit more testing, but it appears to be a limitation of https://github.com/jhillyerd/enmime (which Mailpit uses to parse emails), so I may have to ask there what, if anything, can be done. The email itself does not specify the encoding / character type anywhere, so I think it is guessing (wrong).

**Comment by rogerdz** [comment]
I don't have much experience with go, but in nodejs email processing library (example: https://github.com/mazira/mailparser-mit) there is an option defaultCharset (set value is utf-8) to handle when email does not specify charset.
You can check https://github.com/jhillyerd/enmime to see if there is something similar ^^

**Comment by axllent** [comment]
I believe we've [gotten to the bottom of it](https://github.com/jhillyerd/enmime/issues/266). The problem here is that the [email RFC](https://www.w3.org/Protocols/rfc1341/7_1_Text.html) clearly states that the default content type for all email is `"text/plain; charset=us-ascii"`, so anything outside of this should be set in the email headers. Whilst the email library Mailpit uses does try guess this (if not set), it is not reliable.

In your case you should be defining the correct content type in your email headers to handle the characters, and not expecting the email client to guess correctly.

**Comment by axllent** [comment]
I can confirm that (using your example) setting setting the `Content-Type: text/plain; charset="UTF-8"` header in your email headers fixes the issue entirely in the UI as the mail parser in Mailpit (or any email program) then knows what character set to use when decoding the email :+1:
