### ISSUE TITLE
SMTPAddressFailedException: 452 4.5.3 Too many recipients

### ISSUE THREAD

**Issue by peter-bielik-atos** [axllent/mailpit#205]
Hello.
First of all, thank you for your great tool.
Currently, we are migrating from MailHog to MailPit & during our tests, we have found out, that, when email contains more than 100 recipients, it reports back status code "452 4.5.3 Too many recipients" and sending operation fails.
Is there a way to configure total number of recipients (enviroment variable or cmd line switch)?

Many thanks. :)

**Comment by axllent** [comment]
You're welcome @peter-bielik-atos! Unfortunately this 100 recipient limit is imposed (hardcoded) in the SMTPD package Mailpit uses ([see here](https://github.com/mhale/smtpd/blob/master/smtpd.go#L428-L430)) - probably due to the fact that RFC 5321 states that an SMTPD server must handle at the very least a maximum of 100 recipients (you'll need to search for that and read a lot of documentation of RFC 5321 to verify). Many mailservers do in fact impose a maximum of 100 recipients including Gmail, so this is probably a safe limit for testing purposes.

In order to make this configurable in Mailpit, either mhale/smtpd needs to make this configurable (preferable), or I have to bundle a modified version of it into Mailpit (I'd really prefer to avoid this).

How many recipients are you actually trying to send with?

**Comment by peter-bielik-atos** [comment]
Hello.
It depends on the testcase, could be up to 400-500 recipients...
Anyway, thank you for the clarification, we will try to solve this other way at our side...
Please, add this info regarding limit to the documentation.
Thank you.

**Comment by axllent** [comment]
Thanks for the tip. I have added this now to [the documentation](https://mailpit.axllent.org/docs/configuration/troubleshooting/#452-453-too-many-recipients) in the meantime. I do understand that having this configurable, so I have opened [a ticket](https://github.com/mhale/smtpd/issues/39) to see if the module maintainer is open to this.

**Comment by peter-bielik-atos** [comment]
You are great!
Thank you very much for the smtpd ticket... :)

**Comment by axllent** [comment]
@peter-bielik-atos This is just a heads-up that `mhale/smtpd` has now added support as per my quest to set the maximum recipients (still default 100), so I have implemented this feature in Mailpit too (not yet released). I expect to release a new version of Mailpit later this week.
