### ISSUE TITLE
Empty web interface email message

### ISSUE THREAD

**Issue by cromatyt** [axllent/mailpit#209]
First of all, thank you for this projet.

I try it with docker v24.0.6 and your images tags : v1.10 / v1.9.10 and v1.8.4.

When I send emails, I got them as a list in the "home" webpage.
If I open one of them, I have the left panel (message date, size and return button) Ok but an empty message view.
I test it on latest chrome/firefox/safari browser.

Work fine with v1.5.2 (I pick a random old one).

Best regards

**Comment by axllent** [comment]
Hi @cromatyt . That doesn't sound good at all! This is the first report of this kind of issue so I'm really keen to find out what is causing this is your side, especially since you get the error in all browsers.

It sounds to me like it is a JavaScript error, so the first thing I would like you to try is to open a message when you have your developer tools open in your browser. You can usually toggle this open/close by pressing F12 on your keyboard. Is there anything displayed in the errors tab when you try to open the message, and if so what?

**Comment by cromatyt** [comment]
Thank for the quick answer.

Yes you are right, I have 3 typeError (app.js) with the latest image tag:
- e.message.From is null (2 time)
- document.querySelector(...) is null

More details :
- I don't have any browser extension for this test
- I use only 2 env var: MP_UI_AUTH and MP_DATA_FILE

**Comment by axllent** [comment]
Please could you provide me with a copy of a raw message which is giving you this error? I mean the entire message including headers etc.

**Comment by axllent** [comment]
Actually - don't worry about sending me a copy of the email, I can replicate the error simply be omitting the `From` header in an email. I will release a fix for this in the next 12 hours or so. Thank you for reporting the error!

**Comment by cromatyt** [comment]
Oh yes, i forgot to explain how i test it sorry.
I use telnet to send email and as you mentioned, i omit 'from' and 'to' fields and only use 'MAIL FROM' and 'RCPT TO'.
Anyway, thank you !

**Comment by axllent** [comment]
@cromatyt A fix for this has just been released in [v1.10.1](https://github.com/axllent/mailpit/releases/tag/v1.10.1). Please confirm whether this resolves your issue? Thanks again for reporting this.

**Comment by cromatyt** [comment]
It's perfect.
I really appreciate how quickly you took care of it !

**Comment by axllent** [comment]
Excellent, and you are very welcome! :)
