### ISSUE TITLE
Clicking on URL raises "Content Security Policy «frame-src»" error

### ISSUE THREAD

**Issue by antonkomarev** [axllent/mailpit#22]
When clicking on URL in email we are getting CSP error in console (and link not opening).

> Content Security Policy: Page parameters blocked resource loading http://example.com/email-verification/4a7449fbefbc5280dc50e0025c366fd8 («frame-src»).

This issue could be solved by force open all links in new tab.

**Comment by axllent** [comment]
Thanks for raising this @antonkomarev - it used to work fine and in the last release I managed to break it :) All links in an email should get the `target="_blank"` appended to them via JavaScript after the iframe loads, but this is firing too quickly before the DOM has loaded (due to the last change). I will fix this very soon.

**Comment by axllent** [comment]
Thanks again for the bug report. This has been fixed in v1.2.9 :+1:
