### ISSUE TITLE
[FeatureREQ]Multidomain usage

### ISSUE THREAD

**Issue by plexmaniax** [axllent/mailpit#231]
It would be great if mailpit could be used in multidomain context.

We've got an agency server with couple of customers, we would like to provide access to mailpit to all of them, but they should see only the mails which belong to the own domain.

mailpit.domain1.tld
mailpit.domain2.tld
mailpit.domain2.tld

Maybe there is a way with a user management instead of domain managing?

**Comment by axllent** [comment]
@plexmaniax I agree with you in that it would be an awesome feature, however multi-account support / mailboxes is not currently in the planning due to the technical overheads and the fact that Mailpit would need a major rewrite to support this. 

The only possible solutions (with Mailpit) would be to run multiple instances of Mailpit on different ports, and then configure each respective website to send mail directly to their respective Mailpit ports - or to separate out your websites into individual self-contained Docker containers (each running their own Mailpit instance). The easiest solution (not using Mailpit) is probably using an off-the-shelf hosted commercial solution such as [Mailtrap](https://mailtrap.io/).

Please refer to #86 & #115 for the same questions & answers.
