### ISSUE TITLE
Suggestion: IMAP/POP server

### ISSUE THREAD

**Issue by oliveiraev** [axllent/mailpit#249]
Is it possible to implement an IMAP or POP server in the project? So I can test the emails in my favorite client, instead of the web UI.

I know I can forward the messages to a real SMTP server, but the reason to use Mailpit is just avoid flooding my mailserver with crap 😕

**Comment by axllent** [comment]
Hi @oliveiraev . This has been asked already a year ago in #72 - which I declined as I had another 100 development priorities at the time. IMAP is very complicated as one deals with various states of email, folders etc (which Mailpit does not have), but POP3 _might_ potentially be a new feature now. I'll have to think about this a bit more and do some research before saying yes or no. Please leave this with me for now.

**Comment by oliveiraev** [comment]
Thanks for the reply and sorry about the duplicated request.

**Comment by axllent** [comment]
@oliveiraev This ended up being more complicated that I had anticipated because I had to write a complete POP3 server from scratch. Fortunately POP3 is one of the most simple protocols around so it wasn't that bad....

I have released this feature in [v1.14.0](https://github.com/axllent/mailpit/releases/tag/v1.14.0) and the documentation can be found on [the website](https://mailpit.axllent.org/docs/configuration/pop3/). Please read the notes in the documentation and let me know if you have any questions, and confirm whether this works as you expected? Thanks.

**Comment by axllent** [comment]
@oliveiraev I would really appreciate if you could confirm that this is working for you. Thanks.

**Comment by Novapixel1010** [comment]
@axllent So far via cli it works. Thanks so much for this project it really saved lot of headache 🤯 of setting up a whole server. When all need to do is test before production.  I can test it more if you would like?

```shell
frappe@crm5-dev:~/frappe-bench$ telnet pop.in.com 1110
Trying 192.168.1.213...
Connected to pop.in.com.
Escape character is '^]'.
+OK Mailpit POP3 server
quit
+OK goodbye
Connection closed by foreign host.

```

**Comment by axllent** [comment]
Thanks for the feedback @Novapixel1010 , I'm glad to hear you find it useful!
