### ISSUE TITLE
Ux improvement: view previous message button could update when there's a new email available

### ISSUE THREAD

**Issue by epicwhale** [axllent/mailpit#272]
Just sharing a productivity pain point, incase others face it too:

The "View Previous Message" button (triangular left arrow) does not update in tandem with the "Return" button indicating there is a 'newer email' available.

Left action disabled
![image](https://github.com/axllent/mailpit/assets/670655/9e8309ac-48b1-443e-a419-45d4d569f6ac)

Despite
![image](https://github.com/axllent/mailpit/assets/670655/bb27c41d-537b-4c4c-a3c9-c85b798a87e0)

So to quickly access the latest email, I need to go back to the main inbox view, and then tap.

Expected: Triangular left arrow button at top right is available whenever a new mail is detected, so can jump to it directly.

**Comment by epicwhale** [comment]
Oops, I just spotted the popup that appears when new mails arrive at the bottom right (missed it on my large monitor earlier). That does the job!

![image](https://github.com/axllent/mailpit/assets/670655/c9b587fb-c003-47c1-8b25-d8d10a7a4d5a)

**Comment by axllent** [comment]
@epicwhale Thanks for the feedback. Yes, I am aware of this "issue", but it's more of an "issue by design" than an oversight/bug. When a message is clicked in the message listing, the `<prev>` - `<next>` button logic is taken from the **current** view, and not dynamically changed when new messages are received. The reason is that the message listing can change very quickly (between 100-200 messages per second) which would completely change the logic of what is the next message on that page - so what you are viewing may not even be listed on on the current page any more (moved to another page based on the number of messages per page).

It is not ideal, I know, but the confusion it would potentially cause if it dynamically changes on every new  received message is not worth it. As you've seen, there are notifications when new messages are received, so this is one of the work-arounds to at least allow a user to load the latest message while viewing another.
