### ISSUE TITLE
log-file option, status display

### ISSUE THREAD

**Issue by gitgrub** [axllent/mailpit#282]
No real issue, just a picky wish.
1. when using the --log-file switch, I would like to see the messages on screen, too.  Screen is for now, log file is "for ever", for search.
2. it might be a bit nicer to vertically align the "msg=" string on screen and log when using --verbose.

What do you think?

**Comment by axllent** [comment]
Hi @gitgrub.

Whilst I always try satisfy every request, there are limits ;-)

> when using the --log-file switch, I would like to see the messages on screen, too. Screen is for now, log file is "for ever", for search.

No sorry, the whole point of the `--log-file` is to prevent the console from "getting spammed", and of course to keep a more permanent and easily accessible record (log file). If you wish to see a "live version" you can always `tail -f <logfile>` which should give you realtime events.

> it might be a bit nicer to vertically align the "msg=" string on screen and log when using --verbose.

Whilst I agree with you from a cosmetic point of view, it's not supported. The log format is determined by [logrus](https://github.com/sirupsen/logrus) which states "the output is compatible with the [logfmt](http://godoc.org/github.com/kr/logfmt) format" - so clearly this is a defined format, I suspect to allow parsers to process the data, and of course because log files are not designed to be pretty.

Sorry, I can't really help you here...
