### ISSUE TITLE
Invalid from address

### ISSUE THREAD

**Issue by dejudicibus** [axllent/mailpit#294]
I installed mailpit and started it.  I can see the MailPit interface on localhost:8025 as expected.
Then I created a file email.txt as follows

```
From: sender@example.com
To: recipient@example.com
Subject: Email Subject

This is the body of the email.
It can contain multiple lines of text.
```

but if I call MailPit as follows

```
mailpit sendmail < email.txt
```

I get the error message

```
invalid from address
```

and no messages in the browser interface. Changing the from address to ANY real or fake address makes no change.

Platform: Windows 10 Pro with WampServer 3.2.6 64bit

**Comment by axllent** [comment]
That's really strange - I just tried with a copy/paste of your syntax and it works perfectly for me.  I can't see any reason it would/should fail, unless potentially the txt file you created contains maybe some strange or unsupported hidden character encoding - what did you use to create the text file? 

What happens if you try with this file? [1-test.txt](https://github.com/axllent/mailpit/files/15292027/1-test.txt)

**Comment by bmunshi** [comment]
I am also getting same error 

`invalid from address`

Tried with [1-test.txt](https://github.com/axllent/mailpit/files/15292027/1-test.txt)

Still same error

**Comment by axllent** [comment]
@bmunshi on what platform is the `mailpit sendmail...` being run? I assume for both of you that you're on a recent version of Mailpit too?

**Comment by dejudicibus** [comment]
I found out what the problem was. If I call just `mailpit` I get the error. 
To avoid the error I have to call

```
mailpit -s localhost:1025 -l localhost:8025

```

I thought that localhost was the default, whereas the default is 0.0.0.0 in both cases (1025 & 8025)

**Comment by axllent** [comment]
I am confused @dejudicibus - `0.0.0.0` means the Mailpit server should **listen** on all network interfaces which is the default (ie: not just to "localhost") which should work on Windows too, and the argument you are running is to start the Mailpit server, not to send messages via `mailpit sendmail < email.txt` (which is the issue you reported).

So `mailpit -s localhost:1025 -l localhost:8025` starts mailpit and listens to "localhost" only (other machines in your network cannot connect), and `mailpit sendmail < email.txt` should then be able to send to Mailpit.

**Comment by axllent** [comment]
@dejudicibus & @bmunshi - I have found the cause. When using sendmail in this way (without specifying a sender's email in the command with `-f`), it will automatically detect your username from the system. The issue here is that Windows returns the "user" in the format `hostname\username` - and `\` is not a valid character in an email ~ so you get the error.

I have just pushed a fix (work-around) in [v1.18.2](https://github.com/axllent/mailpit/releases/tag/v1.18.2) which will fix this issue for both of you. Please confirm this works for you? Thanks.

**Comment by powerquell** [comment]
I´m running into the same issue when trying to connect and test via telnet.

```
220 deadc8e0468a Mailpit ESMTP Service ready
EHLO test.example.com
250-deadc8e0468a greets test.example.com
250-SIZE 0
250-AUTH LOGIN PLAIN
250 ENHANCEDSTATUSCODES
MAIL FROM:test@example.com
501 5.5.4 Syntax error in parameters or arguments (invalid FROM parameter)
```

Mailpit is running via Docker-Compose and is v1.18.2.

Container log is not showing any error
````
    
time="2024/05/17 14:20:47" level=info msg="[smtpd] enabling any authentication (insecure)"
time="2024/05/17 14:20:47" level=info msg="[smtpd] starting on [::]:1025 (no encryption)"
time="2024/05/17 14:20:47" level=info msg="[http] starting on [::]:8025"
time="2024/05/17 14:20:47" level=info msg="[http] accessible via http://localhost:8025/"
```

I also tried other domains. But the same error here.

**Comment by axllent** [comment]
@powerquell I don't think this is related to this issue at all. From what I see, your Mailpit requires authentication (`250-AUTH LOGIN PLAIN`), but you're not authenticating via telnet first before issuing the`MAIL FROM`.

**Comment by powerquell** [comment]
@axllent
The variable MP_SMTP_AUTH_ACCEPT_ANY is set to "1". So no login should be allowed?

**Comment by axllent** [comment]
Ahh right - sorry @powerquell, that was not obvious from your original message. Your formatting is incorrect, try `MAIL FROM:<test@example.com>` - the SMTP protocol requires `<>` around the addresses (including `RCPT TO`) ([see this](https://www.rfc-editor.org/rfc/rfc5321.html#section-3.3)).

**Comment by powerquell** [comment]
Thank you. I had mixed something up, thought the name was in the brackets and not the address.
Now it works without any problems.

```
MAIL FROM:<test@example.com>
250 2.1.0 Ok
```
