### ISSUE TITLE
[IMPROVEMENT] Clearer Runtime descriptions

### ISSUE THREAD

**Issue by boomam** [axllent/mailpit#296]
Hi,  
Is there a way for us to contribute to the docs?  
I ask, as the [runtime options](https://mailpit.axllent.org/docs/configuration/runtime-options/) are incomplete when it comes to descriptions and usage.  
&nbsp;  
For example - 
```
--database 
MP_DATABASE 
0
Specify the local database filename to store persistent data.  
The default is a local temporary file which is auto-deleted when Mailpit exists.  
You can optionally optionally use a remote rqlite database by specifying a "http address" ([see docs](https://mailpit.axllent.org/docs/configuration/email-storage/)).
```

Issue here is that there is no guidance on the file format to use, just an example of `0` being the default.  
It would be helpful for others to have an additional line that describes the file being in the format of `/location/on/disk/filename.db` so that new users don't have to trawl the containers contents to find out the file format to use.  
&nbsp;  
As a second example, some variables, that appear to be true/false in nature, are not described as such - 
```
--use-message-dates
MP_USE_MESSAGE_DATES
Use message header date as the Mailpit received date & time instead of the SMTP-received date & time.

--ignore-duplicate-ids
MP_IGNORE_DUPLICATE_IDS
Ignore duplicate messages based on Message-Ids.

--log-file
MP_LOG_FILE
Log Mailpit output to file instead of stdout.

--quiet
MP_QUIET
Quiet logging (errors only)

--verboseverbose
Verbose logging (debug)
```

These should be specified with an example/default of whether they are true, false, 0 or 1.  
&nbsp;  
Happy to contribute to the docs if someone can point me to where to do so?  
&nbsp;  
Thanks.

**Comment by axllent** [comment]
Hi @boomam. Unfortunately the website docs is not a public repo, predominately because the build and deployment process contains sensitive information. Ideally it would be public where everyone can contribute, but it looked to be too complicated when I last investigated it.

Thanks for your feedback - I have made a few alterations to the website docs based on your recommendations - not everything is covered, however displaying the boolean default values was a good tip (thanks!), and the default database value should not have said `0` (oversight/typo). I have tried to reference "further reading" in most of those options where examples are usually given, though it's a fine line between providing too little and too much information.

So given the above, I believe that Github issues will have to suffice for modifications to the documentation. It's not ideal, I know.
