### ISSUE TITLE
[Feature request] - Multi-tenancy on single instance of Mailpit

### ISSUE THREAD

**Issue by arxeiss** [axllent/mailpit#301]
Hello,

I'm now maintaining project for organization that is educating girls in IT. We have 1 instance of testing application for each team (now 12 teams + 2 lecturers app).

So that means I have to spin up also 14 instances of Mailpit etc. It would be nice to spin up just 1 instance. And just by configuring it I would set up 14 accounts. Meaning 14 different SMTP credentials and 14 different UI accounts. When after login, each account would see only the own emails.

So I'm wondering if you would be OK with implementing (or even accepting PR with) multi-tenancy feature. 
My idea was to reuse tenancy you support now. Meaning if you configure `tenantID` you cannot setup multi-tenancy and vice-versa.

Then if you setup multi-tenancy (new seciton in config), it would contain section for users and SMTP credentials. Then the rest of code would require minimal changes. As I would be reusing existing Authentication and existing tenant usage.

However, I need to handle that by this Saturday. So I might not be able to prepare PR now and I will end up spinning 14 instances anyway. But for future courses I might be preparing that.

**Comment by axllent** [comment]
Hi @arxeiss. This feature request has come up a couple of times in the past, but I do not believe it is "that simple". Recently I added tenancy database support which would assist in this feature, however the complication would arise on both the frontend (web UI) as well as the SMTP as to routing & access. Mailpit was never designed to be multi-user, and I suspect that in order to make it so, a huge portion would have to be rewritten, as well as potentially break backwards-compatibility (specifically SMTP and API).

That last part is a deal-breaker - if adding multi-user support meant that changes are required in the API, then this is an absolute no-go.

I understand your point - setting up multiple instances for your use-case, but you will likely have a much easier time scripting a multi-deployment script than trying to change Mailpit. I don't want to discourage you though, as I think there are some cool features that could be gained by adding multi-user, I'm just preparing you to expect complications. I would definitely consider a PR to add this functionality, provided of course it is backwards compatible.

**Comment by mtangoo** [comment]
what about making a binary that simply spins multiple mailpit processes. that way only proc management is added and mailpit works same way
