### ISSUE TITLE
[Feature Request] Add support for testing dark mode

### ISSUE THREAD

**Issue by mansoorkhan96** [axllent/mailpit#304]
This is a feature request to test the dark mode support of an email.

Inspiration: https://proofjump.com/dark-mode-simulator/

**Comment by mansoorkhan96** [comment]
Never mind!

It already works but it adopts the system theme not the theme you are switching in Mailpit UI.

**Comment by axllent** [comment]
The dark mode setting is actually for the Mailpit UI, and not how emails are rendered (they are always rendered in "light mode", ie: the standard). Dark mode in emails this is not as simple as it may sound, in fact it is very complicated, and each (of the very few) email clients that do have a native "dark mode" all apparently render this in their own unique / different way. In reality there appears to be no actual standard for dark mode emails, and thus almost no adoption (as far as I am aware). Email programs are a mess, really.

The website you linked to actually hardcodes the font, link and background colours for every html element in an email - very different to how a web browser applies dark mode for supporting websites, and likely very different to each of the few clients that support dark mode. 

I believe that trying to support this feature in Mailpit (ie: a "fake" way of emulating dark mode) would only result in tonnes of bug requests with users expecting different results because their XYZ client does it differently. Please have a look at https://www.litmus.com/blog/the-ultimate-guide-to-dark-mode-for-email-marketers to see what I mean.

**Comment by mansoorkhan96** [comment]
Agreed.
And because it can still adopt the system dark/light mode, we are still able to test. In case anyone trying to test the dark mode, just switch to dark mode at system level and mailpit or the browser itself should respect the preference.

closing this, as its not an issue anymore.

thanks for great work, Ralph ❤️
