### ISSUE TITLE
not receiving any emails with localwp

### ISSUE THREAD

**Issue by megsra17** [axllent/mailpit#313]
I have this Local host website through localwp and there using your email server for test. And im not receiving any emails at all. Im not really sure who to reach out too

**Comment by axllent** [comment]
Hi @megsra17. I've seen quite a few questions relating to Mailpit on the [official localwp forums](https://community.localwp.com/search?q=mailpit), and know there is a bug regarding using localwp using apache on Windows ([see here](https://community.localwp.com/t/mailpit-is-not-intercepting-email-messages-windows/41854/5)). I can't provide any support though for localwp as I do not use that, so your best option would be to search and use their forum instead. If it turns out to be a Mailpit bug, then that is something I can help with :+1:
