### ISSUE TITLE
UTF-8 Email text is not decoded correctly

### ISSUE THREAD

**Issue by antonionardella** [axllent/mailpit#318]
Hello!

The email text is not decoded correctly on the website:
![image](https://github.com/axllent/mailpit/assets/7383572/f25f71bb-a437-4f97-a7e9-0c2c7707282f)
![image](https://github.com/axllent/mailpit/assets/7383572/b34dec34-e4f6-43a2-b216-c3095092d46e)

If you can tell me where to look, I can try to fix that.

Best,
Antonio

**Comment by axllent** [comment]
I've seen this before, and I don't think it's a Mailpit issue at all but rather an email encoding issue (not encoding the subject header correctly and not specifying utf8 encoding for the body). Please could you attach a raw copy of an email (including header and body) which has this problem so I can test? Thanks.

**Comment by antonionardella** [comment]
The email itself is then shown correctly and the raw email is here:

```
Return-Path: <thomas.egger@schule.suedtirol.it>
Received: from zammad-web (localhost [127.0.0.1])
        by zammad-web (Mailpit) with SMTP
        for <noreply_ticket@snets.it>; Thu, 20 Jun 2024 10:08:48 +0000 (UTC)
Message-ID: <559381.105096207-sendEmail@zammad-web>
From: "thomas.egger@schule.suedtirol.it" <thomas.egger@schule.suedtirol.it>
To: "noreply_ticket@snets.it" <noreply_ticket@snets.it>
Subject: RE: Email Testing [Ticket#202406201000188]
Date: Thu, 20 Jun 2024 10:08:48 +0000
X-Mailer: sendEmail-1.56
MIME-Version: 1.0
Content-Type: multipart/related; boundary="----MIME delimiter for sendEmail-108049.040501104"

This is a multi-part message in MIME format. To properly display this message you need a MIME-Version 1.0 compliant Email program.

------MIME delimiter for sendEmail-108049.040501104
Content-Type: text/plain;
        charset="iso-8859-1"
Content-Transfer-Encoding: 7bit

Danke dir, alles gelöst

------MIME delimiter for sendEmail-108049.040501104--
```

As shown `gelöst` is written correctly here

**Comment by antonionardella** [comment]
The word is displayed correctly within the raw email and in the mail client

**Comment by axllent** [comment]
Ahh yes, I see what is confusing you. The RAW message is displayed using UTF-8 because that is the default in Mailpit, and the raw message contains everything (headers, message parts etc). The issue here is that the email itself specifies that the encoding for the text part is encoded with (and so also should be decoded with) `iso-8859-1` which is **not correct**. The email client is ignoring the `iso-8859-1` (which it shouldn't be, but I can't comment on that). 

Just to be clear, Mailpit is displaying the message correctly (doing exactly what it should), the problem here is the message itself.

This fails (what you are getting).... 
```
From: <test@test.com>
To: <test2@test.com>
Subject: Bad encoding
MIME-Version: 1.0
Content-Type: multipart/related; boundary="----MIME delimiter for sendEmail-108049.040501104"

This is a multi-part message in MIME format. To properly display this message you need a MIME-Version 1.0 compliant Email program.

------MIME delimiter for sendEmail-108049.040501104
Content-Type: text/plain;
        charset="iso-8859-1"
Content-Transfer-Encoding: 7bit

Danke dir, alles gelöst

------MIME delimiter for sendEmail-108049.040501104--
```

This however renders the message correctly:
```
From: <test@test.com>
To: <test2@test.com>
Subject: Bad encoding
MIME-Version: 1.0
Content-Type: multipart/related; boundary="----MIME delimiter for sendEmail-108049.040501104"

This is a multi-part message in MIME format. To properly display this message you need a MIME-Version 1.0 compliant Email program.

------MIME delimiter for sendEmail-108049.040501104
Content-Type: text/plain;
        charset="UTF-8"
Content-Transfer-Encoding: 7bit

Danke dir, alles gelöst

------MIME delimiter for sendEmail-108049.040501104--
```

The fix is that sendEmail should be encoding the message part using `charset="UTF-8"`, not `charset="iso-8859-1"`.
