### ISSUE TITLE
Feature request: Inapp screenshots

### ISSUE THREAD

**Issue by baiomys** [axllent/mailpit#320]
Greetings, your program is nearly perfect solution as SMTP to Telegram gateway.
I use it in docker together with https://github.com/gogap/go-wkhtmltox and https://github.com/ncarlier/webhookd
Bash script (70 lines) does all the job.

Could you integrate go-wkhtmltox in you API to make screenshots (and even pdf) directly without extra overhead?
It exists in form of go library.

**Comment by axllent** [comment]
Hi @baiomys. I'm glad to hear you have a nearly perfect solution for your gateway. 

Regarding native screenshot support (which is I think what you are asking for) - No sorry, that is just not possible, at least not possible without the reliance on many third party tooling which Mailpit then becomes dependent on, meaning it would no longer just be a single self-contained binary. 

To generate things like screenshots a web rendering engine must be used (often Webkit/Chromuim or Gecko/Firefox) . This is why utilities such as wkhtmltopdf (which gogap/go-wkhtmltox uses) all require thinks like the QT webkit engine installed which they then call in the background. These engines require a whole series of graphical dependencies to be installed too (in the Docker image). 

If I was to bundle all of that into the Mailpit Docker image, then:
- the Docker image would increase from 10MB to a 500MB+ just contain the requirements
- the Mailpit binary would not work on all platforms without having all those system dependencies installed
- the Mailpit binary would not longer be a static binary due to the reliance on system libraries (C/C++)
- the Mailpit binary would become much bigger
- there would very likely be licencing issues when you consider all the dependencies

> It exists in form of go library.

I'm curious as to which library you mean, but I'm pretty sure it is just a wrapper to use something like wkhtmltopdf under the hood, which then brings us straight back to the list I posted above.

**Comment by baiomys** [comment]
Thank you for quick response, it's late at night in NZ now I guess. =)
I got you point, size and portability matters.

**Comment by axllent** [comment]
It is getting late - but that's sometimes the best time to work on open source ;-) Exactly, size and compatibility matter a lot.
