### ISSUE TITLE
Mail Relay to Mailgun Always Fails

### ISSUE THREAD

**Issue by designermonkey** [axllent/mailpit#337]
Sorry if this is not the correct place to raise this, but I am tearing my hair out with this configuration.

I have settled on the following config to actually allow a connection to Mailgun (none of the other ports or option combinations work).

```
      MP_SMTP_RELAY_ALL: true
      MP_SMTP_RELAY_HOST: ${MAILGUN_HOST}
      MP_SMTP_RELAY_PORT: ${MAILGUN_PORT}
      MP_SMTP_RELAY_USERNAME: ${MAILGUN_USERNAME}
      MP_SMTP_RELAY_PASSWORD: ${MAILGUN_PASSWORD}
```

When I send an email to Mailpit, I get the following logs:

```
mailpit-1  | time="2024/07/24 10:38:36" level=debug msg="[smtpd] allow LOGIN login:\"microngroup\" from:172.18.0.4"
mailpit-1  | time="2024/07/24 10:38:37" level=warning msg="error response to RCPT command for me@something.com: 550 5.7.1 Relaying denied"
mailpit-1  | time="2024/07/24 10:38:37" level=error msg="[smtp] error relaying message: error response to DATA command: 503 RCPT command expected"
mailpit-1  | time="2024/07/24 10:38:37" level=debug msg="[smtpd] received (172.18.0.4) from:noreply@something.com subject:\"My Subject\""
```

I have tried to look this up with Mailgun and helpfully, they simply state that I am [not configured correctly](https://help.mailgun.com/hc/en-us/articles/360012360833-Why-did-I-receive-the-error-Relaying-Denied-or-some-variation-thereof#01GCQEXFED01D7FV9P3JDY46VM:~:text=scenario%20you%27re%20experiencing.-,Response,-is%20from%20Mailgun).

Is there any way to get better verbose logging ( have enabled it with `MP_VERBOSE: true`, as this is not very verbose at all. It would be helpful to be able to see that message and headers that are being sent, and the exchange details in the relay communication between servers.

Other than that, is there anything that experience might help me out here with as I don't understand why it would be failing.

**Comment by designermonkey** [comment]
I have switched to Postmark to see if it was specific to Mailgun, and it is working ok now after adding `MP_SMTP_RELAY_AUTH: plain` and `MP_SMTP_RELAY_STARTTLS: true`.

I do think that more verbosity in logs would be helpful, but I added `tcpdump` to the image and watched that. It didn't help me as I'm not sure what I was looking at, but it might help others.

**Comment by axllent** [comment]
Hi @designermonkey. What I can tell you is that it works fine (to Mailgun) for me. 
```
host: smtp.mailgun.org
port: 587
auth: plain
starttls: true
username: xxx
password: xxx
```
So as you noted with postmark, you need to set at least the **auth** type as well as (in the case of these SMTP servers, **starttls**). **Port** is probably also recommended.

When you say better/more verbose logging, I'm not sure how that would exactly have helped you here. I can clearly see `error response to RCPT command for me@something.com: 550 5.7.1 Relaying denied`. Why Mailgun returned this is unclear regardless how much verbose logging there was, as SMTP error messages can literally say anything - it is the SMTP code which is important.

I will look into more verbose logging, although as I said, I'm unsure how that may necessarily have helped you because the server simply refused to accept your non-authenticated connection (because you did not specify it).
