### ISSUE TITLE
Feature Request - Add option to Enable-Disable Version Check in "About" Section

### ISSUE THREAD

**Issue by alexkved** [axllent/mailpit#339]
### Description
When a user navigates to the "About" link in the Mailpit UI, a context window opens with information and performs a version check of the Mailpit (v1.19.3) Docker version. This version check impacts performance, because external connections could be blocked or not allowed. We would like have an option to enable or disable the version check.
 
### Proposed Solution
Introduce an option `MP_VERSION_CHECK` that can be set to `true` or `false`. If set to `false`, the version check will be skipped when accessing the "About" section in the UI. The default value should be `true` to maintain the current behavior.
 
### Environment Variable:
- `MP_MAILPIT_VERSION_CHECK=true` (default)
- `MP_MAILPIT_VERSION_CHECK=false`
 
### Benefits
- Improved performance for users who do not require the version check.
- Greater flexibility in configuring Mailpit for different environments and use cases.
- Compliance with enterprise policies that do not allow version checks.
 
Thank you for considering this feature request.

**Comment by axllent** [comment]
I am reluctant to add options like this because I see this feature being used primarily to hide the fact that the software does not get updated. To be clear, this is not an automated background update check, this is an on demand "what is the latest version" check which is only done when the modal is opened.

Are you able to share some more information on enterprise policies that do not allow version checks?

**Comment by axllent** [comment]
Thanks for the response. I have given this more consideration and can conclude that, while I understand your logic, there are two main points to note here:

1. This would only address the one "issue" (the version download). Mailpit also requires network/internet communication for various other tasks such as:
   1. Link & HTML checking
   2. Screenshots (which uses proxied images/CSS etc)
   3. Optional extras such as SpamAssassin integration, SMTP release etc (I am aware that these two are likely intranet though)
2. Preventing the application from checking the latest release version (which is only done on demand if the "about" is clicked) would require another CLI flag and a matching environment setting. As there are already a lot of Mailpit options, I have to be very considerate when adding new ones, especially when they have little benefit / effect.

I do value your input and request, however I am going to politely decline this request. If you are concerned about timeouts / delays in the application, then internet connections should be rejected rather than dropped as that will give an immediate failed response.

I hope that makes sense to you?

**Comment by alexkved** [comment]
Thanks a lot for your detailed explanation. I completly understand your argumentation. Keep up your excellent work!
