### ISSUE TITLE
Share smtp/webUI with different subdomain

### ISSUE THREAD

**Issue by camlafit** [axllent/mailpit#360]
Hello

I'm not sure how to formulate my question then sorry for this first opening.

We would propose on a shared hosting a mailpit instance to each different users. 
Actually we could start different instance and set a different ports to each account. But is not convenient as we need to open many ports and provide different proxy configuration to match instance with user.

If I've underestood correctly, some element are yet present to manage different tenant with same instance. In this case our shared user hosting could be identified as different tenant.

Could be possible to provide to difference service as smtp/web ui an environnement value to associate tenant value ?

Thanks a lot

**Comment by axllent** [comment]
Hello @camlafit. I think I understand what you are asking.

Firstly the SMTP protocol does not support subdomains in the same manner HTTP does, so that is not possible (unless subdomains point to different unique IP addresses). 

Secondly, Mailpit does not support multiple users. Mailpit was just not designed for this, and to support Multiple users (and mailboxes) would mean a complete rewrite (which is not going to happen, sorry).

The tenancy support you are thinking of is a database tenancy whereby different instances of Mailpit can use a single hosted **rqlite** database, so this is not what you are looking for either.

The only solution (for what you are trying to do) in in fact either to separate different Mailpit instances (one for each user) on different ports, or on different (virtual?) IP addresses. I don't know how many users you are wanting to support, nor what your network is like, but I see no other option.

**Comment by camlafit** [comment]
Hello

Thanks for your reply. 
As we are with shared hosting, we can have 1 to hundreds accounts, but I think we have to manage less than 10 users requiring an mailpit service.
We can manage it with different ports , we must be a bit intelligent to enable/disable service on the fly. I'll reflect about this and search an approach to manage these instances.

Thanks a lot

**Comment by camlafit** [comment]
I think, we can close in this case :)
thanks

**Comment by axllent** [comment]
I'm sorry I can't help :)
