### ISSUE TITLE
Mailpit shows wrong version in about.

### ISSUE THREAD

**Issue by N6REJ** [axllent/mailpit#376]
we've verified that we are using 1.20.7 yet it says its 1.20.6
![image](https://github.com/user-attachments/assets/2214726b-50df-4c65-a1b5-58555317a94e)
how can we see whats going on?

**Comment by axllent** [comment]
Hey @N6REJ. This same thing happened to you before in #357. The release version numbers are set automatically as the release is being compiled and packaged, so this is not technically possible - if you downloaded and installed 1.20.7 then that is what it is. 

You can verify on the commandline (in the directory with the mailpit.exe file) by running `mailpit version`. If that shows you the correct version but the web interface doesn't, then you need to restart your stack because you somehow still have the old version running in memory. If however that is showing you an older version, then you have downloaded the wrong version.

**Comment by axllent** [comment]
If you need additional support, please provide me the link to your version and I can then manually compare and verify with what's on GitHub in the releases. Thanks.

**Comment by N6REJ** [comment]
Sorry to have bothered you.  I looked for the other ticket cause I remembered this happening once before.
I've no clue how but somehow we had the wrong version from your release.

**Comment by axllent** [comment]
No worries. Seeing as this is the second time this has happened (and assuming they were caused by the same issue), I'm curious as to how you are configuring your versions in [the app](https://bearsampp.com/) - it is an automated or manual process?
