### ISSUE TITLE
[feature-request] Add mailpit instance ID (MP_LABEL) to hook json.

### ISSUE THREAD

**Issue by baiomys** [axllent/mailpit#400]
Sometimes it is necessary to make API callbacks from hook processing code, for example to delete messages with unknown recipients.
Client IP is not reliable enough to determine API URL for callbacks.

**Comment by axllent** [comment]
That makes sense. Currently the webhook is a 1:1 "copy" of a message summary (the same as the web UI has), so I don't think it's a good idea to clone / modify the object for every message just to add a new field because there could be 100+ messages per second (wasted CPU).

Would an additional HTTP header work with the webhook request? I'm thinking something like `Mailpit_Label: blaah` if the label is set - easy to implement, and no wasted CPU.

**Comment by baiomys** [comment]
Great! Header should be fine, tnx. 

It would be nice also to somehow include info about absent html part.

Hook code generates 

1. preview link for telegram bot, pointing via Caddy/Nginx to view/{ID}.html, 
2. in some cases preview image of HTML content

mailpit return error code which MUST be handled on reverse proxy side, it would be better not to send link and do not call image generation API (which is really CPU hungry) at all in case there is no HTML.

**Comment by axllent** [comment]
Adding the header isn't an issue (and I will do this), however your other request to add an extra field is problematic because it introduces the same problem I explained earlier: The webhook receives the same "MessageSummary" that the browser's websocket connection receives - which does not include any HTML or Text (other than a "snippet" summary).

I am assuming your Telegram bot has logic built in? When it receives a webhook, can it not call the API and determine that itself?
- Incoming webhook has message ID `XwxLXpPvasMibz9GbX5ZaB`
- Telegram bot does a HTTP request to Caddy/Nginx proxy to `<https://<server>/api/v1/message/XwxLXpPvasMibz9GbX5ZaB`
- Telegram bot can decide what to do based on the value of HTML (or Text as a fallback) etc

**Comment by baiomys** [comment]
> I am interested to hear what you are building that is going to be receiving tousands of webhook connections per minute?
public SMTP to telegram gateway hosting on dozen of VPS worldwide

**Comment by axllent** [comment]
This feature has just been released in [v1.21.6](https://github.com/axllent/mailpit/releases/tag/v1.21.6) :+1:
