### ISSUE TITLE
key/pem handling for smtp

### ISSUE THREAD

**Issue by paulbalomiri** [axllent/mailpit#5]
trying here to configure `smtps` and  `STARTTLS` (optional) for the docker image. 
I can also rebuild the docker image [**EDIT** id nessesary ] and already have let'sencrypt  the key & cert.

The [wiki's smtp page](https://github.com/axllent/mailpit/wiki/SMTP-with-STARTTLS-and-authentication) mentions the config options `--smtp-ssl-cert` and `--smtp-ssl-key`

I can not set them, though & don't know if it is possible from env variables too (trying to avoid the `execute` docker config service option if possible.

**Edit 2**: The codebase's config.go also does not mention these options...

Thumbs up for the project 👍

**Comment by paulbalomiri** [comment]
ah, now saw your commit from 2hrs ago:

https://github.com/axllent/mailpit/commit/56fdaa1224fbdb768758889fd8e18fb3bfada309

Does this mean the `MP_SSL*` are taken from the web UI?

https://github.com/axllent/mailpit/blob/ba8c4cd2aa58c2add42ed1e007506a48c765768a/cmd/root.go#L96-L103

My usecase is served best if i can reverse proxy the UI with traefik, but expose the smtp endpoint as is on a dedicated port (no virtual hosts for smtp)

**Comment by axllent** [comment]
@paulbalomiri It seems there is some confusion, probably caused by me trying to edit multiple documents at the same time.

So to answer your question(s), `MP_SSL_KEY` & `MP_SSL_CERT` have been replaced with `MP_UI_SSL_CERT` and `MP_UI_SSL_KEY` - but these are for the web UI, not SMTP (and in saying that I just realized I have a typo in my code so I have just released 0.1.1). What you are looking for has now been documented in the [wiki](https://github.com/axllent/mailpit/wiki/Runtime-options)  - `MP_SMTP_SSL_CERT` & `MP_SMTP_SSL_KEY`.

Hopefully this answers your questions, and thanks for the heads-up.

**Comment by paulbalomiri** [comment]
#6  and #7 both solve a minor issue regarding this.

Thanks for this great Repo @axllent !
