### ISSUE TITLE
Logs flooded with RunValueLogGC() messages

### ISSUE THREAD

**Issue by pinoceniccola** [axllent/mailpit#9]
Hello,

I'm running Mailpit in Ubuntu 20.04.4 and log get flooded every few minutes with this message:

```
RunValueLogGC(): Value log GC attempt didn't result in any cleanup
```

which I think is related to CloverDB/BadgerDB. Here's a screenshot:

![Screenshot 2022-08-21 at 17 34 14](https://user-images.githubusercontent.com/4711813/185917679-6381cd24-736a-4f8d-9128-6ddb6fcbf3ac.png)

I also tried to run Mailpit with in-memory storage, but still log get flooded again with another message:

```
RunValueLogGC(): Cannot run value log GC when DB is opened in InMemory mode
```

This is my Mailpit service running:

```
[Unit]
Description=Mailpit
After=network.target
[Service]
User=pi
ExecStart=/home/pi/go/bin/mailpit --data /home/pi/mailbox --max 150
[Install]
WantedBy=multi-user.target
```

Lastly, just to note that the Mailpit process is constantly consuming 2.5~3.5% CPU, which is quite high compared to the Mailhog instance it replaced.

![Screenshot 2022-08-21 at 17 37 46](https://user-images.githubusercontent.com/4711813/185919729-4b7348ed-b8eb-4399-a8bd-c16f248de3a0.png)

mailpit 0.1.5 compiled with go1.19 on arm64.

(Nevertheless, Mailpit still brings a much better experience than Mailhog, thank you for your work!)

**Comment by axllent** [comment]
Hi @pinoceniccola - firstly thanks for the feedback and kind words. The repeated "error" message you are seeing is coming from CloverDB when it runs a periodic 5-minute schedule to "prune" deleted items where possible from the database (passed through to BadgerDB). The maintainer of CloverDB (@ostafen) had indicated he was going to introduce a way to "capture" those error logs (rather than just printing them to stdout, which is what you are seeing) on https://github.com/ostafen/clover/issues/94#issuecomment-1208009030 - but I don't believe he's done that yet. It is harmless so you can ignore it, despite it maybe being a bit annoying.

I am a bit surprised by the constant 2-3% CPU usage though, as, unless it is actively receiving emails at the time, or doing one of those GC cleanups, I can't see any reason why it would be using any CPU at all. The thing is that (now that you mention it) I get that CPU usage here too. I will need to investigate to try and locate the source of the CPU usage and report back.

**Comment by axllent** [comment]
Re: the CPU usage, I am fairly sure this is coming from CloverDB (specifically the v2 alpha branch which Mailpit uses), and I have reported it on https://github.com/ostafen/clover/issues/97 for feedback.

**Comment by pinoceniccola** [comment]
HI @axllent I switched today to the new beta and I'm impressed at the very noticeable new low footprint for both cpu and memory usage! UX is smooth and slick as it was before the transition.

Great work!

**Comment by axllent** [comment]
@pinoceniccola Awesome, thanks for the testing & feedback! I'll consider this resolved then :+1:
