### ISSUE TITLE
Emoji in mail subjects are not displayed

### ISSUE THREAD

**Issue by LeoniePhiline** [axllent/mailpit#92]
Email subject emoji do show up in notifications:

![grafik](https://user-images.githubusercontent.com/22329650/232597468-e77e4c7d-03f2-4d91-b018-0ff9a191ffc5.png)

But they are missing in the message list:

![grafik](https://user-images.githubusercontent.com/22329650/232597571-b949c0a7-c50f-498e-916c-28962f313a63.png)

(Red indicator added to screenshot - not rendered in the browser.)

And in the message detail view:

![grafik](https://user-images.githubusercontent.com/22329650/232597810-3fa0d673-6e5e-49e3-9eb9-ed8b3d109811.png)

(Red indicator added to screenshot - not rendered in the browser.)

However, they are found in the markup / DOM:

![grafik](https://user-images.githubusercontent.com/22329650/232598017-09d3cd5d-bf42-46b8-8f0e-eba344771557.png)

I would expect `system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"` to be sufficient. (`--bs-body-font-family`)

Emoji do render in the message body:

![grafik](https://user-images.githubusercontent.com/22329650/232598493-0e788dbb-d178-4a97-8385-6ff8353569ad.png)

---

The message header (missing emoji) uses Noto Color emoji. Interestingly, the emoji font is mentioned first:

![grafik](https://user-images.githubusercontent.com/22329650/232599600-cfea4898-d8a6-4604-a97a-26484a4e2546.png)

While the body (good emoji) uses Twemoji Mozilla:

![grafik](https://user-images.githubusercontent.com/22329650/232599706-2530dc78-2d7a-49a1-a6f0-66fb3fe073a2.png)

Removing Noto Color emoji from the font face makes emoji show up:

![grafik](https://user-images.githubusercontent.com/22329650/232600148-5e1cc92b-96a7-48e3-835d-b362c80f5be0.png)

---

Firefox 112, OpenSUSE Tumbleweed, Noto Color emoji is installed!

**Comment by axllent** [comment]
Could you please provide me with the message itself (feel free to edit the headers etc to make it anonymous, changing emails etc)? Download the message (in Mailpit), edit, zip and attach? Thanks

**Comment by LeoniePhiline** [comment]
That should be no problem. However, I see this being an issue of the SPA, not the mail content.

I was able to "fix it" by removing Noto Color emoji from the `--bs-body-font-family` custom property defined on the mailpit UI.

Do you have the possibility to try and reproduce this issue with a linux desktop?

**Comment by axllent** [comment]
Yes I do use a Linux desktop (Ubuntu), but I would appreciate a sample message I can test with so I can try reproduce the issue and confirm a fix (or detect what the problem could be) :)

**Comment by LeoniePhiline** [comment]
Hi! Just hopping in to let you know I didn’t forget- I just haven’t yet found the time. :)

**Comment by axllent** [comment]
I found an email with an emoji (utf8 encoded) in a subject and it works fine on my system (Ubuntu 22.04). The emoji is rendered using Noto Color emoji, and if I remove that font from the CSS list Firefox falls back automatically to Twemoji Mozilla (which also works well).

I suspect that the issue here may be due to how your email subject is encoded. If your subject includes the emoji as-is then that may be the issue. My understanding is that the subject field is plain ASCII, and a if the subject requires something like a UTF8 symbol, then it should be encoded properly. Eg: my subject header actually says `Subject: We're on a Sustainability journey =?UTF-8?B?8J+SmeKZu++4jw==?=`.

**Comment by LeoniePhiline** [comment]
# Example mail:

[de0b3dfa-e64c-4bbf-8fa7-09b222b4de85.zip](https://github.com/axllent/mailpit/files/11499037/de0b3dfa-e64c-4bbf-8fa7-09b222b4de85.zip)

(Zipped `.eml` file, as GitHub only accepts a limited number of specific file extensions.)

## Subject line encoding

`Subject: =?utf-8?Q?=F0=9F=94=92?= Secret Cobytes credentials: Test (from
 test env)`

## Display in MailPit - emoji in subject line are _invisible_:

### List view

![image](https://github.com/axllent/mailpit/assets/22329650/8b0d56d0-2676-44f9-bb8f-943fe4b46faa)

### Detail view

![image](https://github.com/axllent/mailpit/assets/22329650/87647191-4a7f-4eba-9313-1453c7fd4e7d)

## Display in MailHog - emoji inn subject line are _visible_:

### List view

![image](https://github.com/axllent/mailpit/assets/22329650/449c6a4b-d7ab-4f82-86be-2ebb4c73395c)

### Detail view

![image](https://github.com/axllent/mailpit/assets/22329650/75dc5d6a-57d0-4175-b036-00460f6a7ea7)

**Comment by axllent** [comment]
@LeoniePhiline Thank you for the detailed report, I really appreciate that. 

Mailpit is currently using the **default** bootstrap 5 font set, which applies to everything in the web UI with the exception of the actual rendered message (iframe / no bootstrap) and desktop notifications. This explains why it is working for the message view, but not in the mail overview, or header summary when opening the message. Clearly there is an issue with "Noto Color Emoji" on your system (ie: your test message works fine on my Ubuntu), however as you have demonstrated, it's actually not needed... at least not on our systems. Apparently you're not the only person with issues with that particular font, so it just seems odd to me that Bootstrap would include this by default (meaning you will have this issue on many bootstrap 5 sites).

I'm happy to remove it from the list of Mailpit CSS fonts as you have requested, and leave it out, provided I don't get bug reports from others that their emojis are not working for them (because the font is missing). I assume that Noto Color Emoji must be included for a compatibility reason, I just don't know for what. I'll see if I can get a release out later today for you :+1:

**Comment by LeoniePhiline** [comment]
That could be real nice!

I believe all emoji fonts can be removed, including "Apple Color Emoji" and "Segoe UI".

If you get bug reports, then please ping me and I'll be glad to help figure them out. :)

**Comment by axllent** [comment]
I do have Android, and can test with Windows 11, however I'd prefer at this stage not to remove all the emoji fonts for the sake of removing them (after all, they must be included by default for a reason). I have released 1.6.10 now - could you please test this and report whether it fixes it for you? Thank you.

**Comment by LeoniePhiline** [comment]
Fixed with https://github.com/axllent/mailpit/commit/d1edbe73b42c45e6bd4c52e146641b46d159d97a ♥️
